// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NackaMatchmaking.API.Data;

#nullable disable

namespace NackaMatchmaking.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402152232_AddPasswordResetFields")]
    partial class AddPasswordResetFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NackaMatchmaking.API.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            Email = "superadmin@itmaskinen.se",
                            FirstName = "System",
                            IsVerified = false,
                            LastName = "SuperAdmin",
                            PasswordHash = "TinTin%26",
                            Role = "SuperAdmin",
                            Username = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Email = "admin@example.com",
                            FirstName = "System",
                            IsVerified = false,
                            LastName = "Admin",
                            PasswordHash = "password123",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "System Settings"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Nacka Företagarträff (Default)"
                        });
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Challenge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallengeOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EventComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EventRating")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAcceptedTerms")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Superpower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuperpowerOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicsOther")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Question", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Placeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId", "Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = "q1",
                            Description = "Inom vilket område kan du bidra med mest värde till andra?",
                            IsHidden = false,
                            Order = 1,
                            TargetRole = "All",
                            Title = "Min Superkraft",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = "q2",
                            Description = "Vad är den största utmaningen du vill lösa just nu?",
                            IsHidden = false,
                            Order = 2,
                            TargetRole = "All",
                            Title = "Min Utmaning",
                            Type = "Choice"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = "q3",
                            Description = "Vad snackar du helst om vid kaffemaskinen?",
                            IsHidden = false,
                            Order = 3,
                            TargetRole = "All",
                            Title = "Samtalsämnen",
                            Type = "MultipleChoice"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = "q4",
                            Description = "Beskriv ditt mål för i år med en mening. AI:n använder detta för att hitta dolda kopplingar.",
                            IsHidden = false,
                            MaxLength = 200,
                            Order = 4,
                            Placeholder = "T.ex. Jag vill expandera min konsultverksamhet till norra Europa...",
                            TargetRole = "All",
                            Title = "Kort om dig",
                            Type = "Text"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Id = "q5",
                            Description = "Beskriv företaget där du jobbar, max en mening 50 tkn.",
                            IsHidden = false,
                            MaxLength = 50,
                            Order = 5,
                            TargetRole = "All",
                            Title = "Kort om företaget",
                            Type = "Text"
                        });
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "QuestionId");

                    b.ToTable("QuestionOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Hjälper andra att växa och sälja mer.",
                            Icon = "🚀",
                            IsHidden = false,
                            Order = 1,
                            QuestionId = "q1",
                            Title = "Försäljning & BD",
                            Value = "sales"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Expert på digitala lösningar och AI.",
                            Icon = "💻",
                            IsHidden = false,
                            Order = 2,
                            QuestionId = "q1",
                            Title = "Teknik & IT",
                            Value = "tech"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Bygger organisationer och team.",
                            Icon = "🎯",
                            IsHidden = false,
                            Order = 3,
                            QuestionId = "q1",
                            Title = "Strategi & Ledarskap",
                            Value = "strat"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Drivkraft för grön omställning.",
                            Icon = "🌿",
                            IsHidden = false,
                            Order = 4,
                            QuestionId = "q1",
                            Title = "Hållbarhet",
                            Value = "sust"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Skriv din egen superkraft.",
                            Icon = "✨",
                            IsHidden = false,
                            Order = 5,
                            QuestionId = "q1",
                            Title = "Annat...",
                            Value = "other"
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Söker leads och nya marknader.",
                            Icon = "📈",
                            IsHidden = false,
                            Order = 1,
                            QuestionId = "q2",
                            Title = "Hitta nya kunder",
                            Value = "leads"
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Söker strategiska samarbeten.",
                            Icon = "🤝",
                            IsHidden = false,
                            Order = 2,
                            QuestionId = "q2",
                            Title = "Nätverk & Partners",
                            Value = "partners"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Behöver stärka upp teamet.",
                            Icon = "🌟",
                            IsHidden = false,
                            Order = 3,
                            QuestionId = "q2",
                            Title = "Rekrytera talang",
                            Value = "talent"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Söker investering eller stöd.",
                            Icon = "💰",
                            IsHidden = false,
                            Order = 4,
                            QuestionId = "q2",
                            Title = "Kapital & Finansiering",
                            Value = "funding"
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Berätta om din utmaning.",
                            Icon = "🏢",
                            IsHidden = false,
                            Order = 5,
                            QuestionId = "q2",
                            Title = "Annat...",
                            Value = "other"
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Möjligheter och hot.",
                            Icon = "🤖",
                            IsHidden = false,
                            Order = 1,
                            QuestionId = "q3",
                            Title = "AI-revolutionen",
                            Value = "ai"
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Lokal tillväxt och miljö.",
                            Icon = "📍",
                            IsHidden = false,
                            Order = 2,
                            QuestionId = "q3",
                            Title = "Nackas framtid",
                            Value = "local"
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Hybridarbete och kultur.",
                            Icon = "🛸",
                            IsHidden = false,
                            Order = 3,
                            QuestionId = "q3",
                            Title = "Framtidens jobb",
                            Value = "future"
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Vad brinner du för?",
                            Icon = "☕",
                            IsHidden = false,
                            Order = 4,
                            QuestionId = "q3",
                            Title = "Annat...",
                            Value = "other"
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Hittar rätt bolag och ser till att de ökar i värde",
                            Icon = "💰",
                            IsHidden = false,
                            Order = 6,
                            QuestionId = "q1",
                            Title = "Kapital & Investering",
                            Value = "invest"
                        },
                        new
                        {
                            Id = 16,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Hjälper människor att må bättre och prestera mer.",
                            Icon = "🧘",
                            IsHidden = false,
                            Order = 7,
                            QuestionId = "q1",
                            Title = "Hälsa & Friskvård",
                            Value = "health"
                        },
                        new
                        {
                            Id = 17,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Skapar arbetsplatser där människor trivs och presterar bättre.",
                            Icon = "🏢",
                            IsHidden = false,
                            Order = 8,
                            QuestionId = "q1",
                            Title = "Lokaler & Arbetsplatser",
                            Value = "facility"
                        },
                        new
                        {
                            Id = 18,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Att hitta rätt mark och lokaler för att din verksamhet ska kunna växa.",
                            Icon = "📍",
                            IsHidden = false,
                            Order = 6,
                            QuestionId = "q2",
                            Title = "Lokal & Mark",
                            Value = "facility"
                        },
                        new
                        {
                            Id = 19,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Att nå fram i bruset och förvandla kontakter till betalande kunder.",
                            Icon = "📣",
                            IsHidden = false,
                            Order = 7,
                            QuestionId = "q2",
                            Title = "Sälj & Marknadsföring",
                            Value = "sales"
                        },
                        new
                        {
                            Id = 20,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Maximera resursutnyttjandet.",
                            Icon = "♻️",
                            IsHidden = false,
                            Order = 5,
                            QuestionId = "q3",
                            Title = "Cirkulär ekonomi",
                            Value = "circular"
                        },
                        new
                        {
                            Id = 21,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Hitta nästa växel snabbt.",
                            Icon = "🌱",
                            IsHidden = false,
                            Order = 6,
                            QuestionId = "q3",
                            Title = "Tillväxt",
                            Value = "growth"
                        },
                        new
                        {
                            Id = 22,
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Description = "Skala upp hållbart imperium.",
                            Icon = "🏛️",
                            IsHidden = false,
                            Order = 7,
                            QuestionId = "q3",
                            Title = "”Romarriket”",
                            Value = "rome"
                        });
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Registration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAcceptedTerms")
                        .HasColumnType("bit");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.SiteSetting", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId", "Key");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "ProfileDescription",
                            Value = "Kontrollera att dina uppgifter stämmer så att andra kan hitta dig på mässan."
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "ProfileTitle",
                            Value = "Mina uppgifter"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "SuccessMessage",
                            Value = "Vi skickar ett mejl med dina personliga matchningar senast 48 timmar innan företagarträffen öppnar."
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "SurveyOpen",
                            Value = "true"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "WelcomeButton",
                            Value = "Starta matchningen"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "WelcomeDescription",
                            Value = "Välkommen till årets matchmaking-event!"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "WelcomeLogo",
                            Value = ""
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "WelcomeTagline",
                            Value = "Matchmaking 2026"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "WelcomeTitle",
                            Value = "Välkommen!"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "AiProvider",
                            Value = "OpenAI"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "AiModel",
                            Value = "gpt-4o"
                        },
                        new
                        {
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Key = "AiApiKey",
                            Value = ""
                        },
                        new
                        {
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "AiProvider",
                            Value = "OpenAI"
                        },
                        new
                        {
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "AiModel",
                            Value = "gpt-4o"
                        },
                        new
                        {
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "AiApiKey",
                            Value = ""
                        },
                        new
                        {
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "SendGridApiKey",
                            Value = ""
                        },
                        new
                        {
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "SendGridFromEmail",
                            Value = "ariel@itmaskinen.se"
                        },
                        new
                        {
                            CompanyId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Key = "EmailFromName",
                            Value = "Nacka Företagarträff"
                        });
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OtherValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("CompanyId", "QuestionId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.UserMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("MatchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("User1Feedback")
                        .HasColumnType("int");

                    b.Property<string>("User1FeedbackReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("User1Interested")
                        .HasColumnType("bit");

                    b.Property<int?>("User2Feedback")
                        .HasColumnType("int");

                    b.Property<string>("User2FeedbackReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("User2Interested")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("User1Feedback");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Feedback");

                    b.HasIndex("User2Id");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.AdminUser", b =>
                {
                    b.HasOne("NackaMatchmaking.API.Models.Company", "Company")
                        .WithMany("AdminUsers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Participant", b =>
                {
                    b.HasOne("NackaMatchmaking.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Question", b =>
                {
                    b.HasOne("NackaMatchmaking.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.QuestionOption", b =>
                {
                    b.HasOne("NackaMatchmaking.API.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("CompanyId", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Registration", b =>
                {
                    b.HasOne("NackaMatchmaking.API.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.UserAnswer", b =>
                {
                    b.HasOne("NackaMatchmaking.API.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NackaMatchmaking.API.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("CompanyId", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.UserMatch", b =>
                {
                    b.HasOne("NackaMatchmaking.API.Models.Participant", "User1")
                        .WithMany()
                        .HasForeignKey("User1Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("NackaMatchmaking.API.Models.Participant", "User2")
                        .WithMany()
                        .HasForeignKey("User2Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Company", b =>
                {
                    b.Navigation("AdminUsers");
                });

            modelBuilder.Entity("NackaMatchmaking.API.Models.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
